[meta]
firstName = "Soham"
lastName = "Parekh"
role = "Software Developer"
about = """I am a software developer creating open source projects and 
  <a href="https://sohamp.dev/">writing</a> about software development, 
  competitive coding, machine learning, cybersecurity and information security awareness.
  I am also the founder of and lead maintainer at Devstation, a not-for-profit 
  organisation with an aim to encourage startups and organisations to adopt 
  open-source tech."""

[meta.location]
city = "Mumbai"
country = "India"
logo = "https://www.flaticon.com/svg/static/icons/svg/330/330176.svg"

[[social]]
name = "github"
url = "https://github.com/und3fined-v01d"
logo = "https://img.shields.io/github/followers/und3fined-v01d?style=social"

[[social]]
name = "linkedin"
url = "https://linkedin.com/in/soham-parekh"
logo = "https://img.shields.io/badge/Linkedin-grey?logo=linkedin&style=social"

[[projects]]
name = "Friend.ly"
url  = "https://github.com/und3fined-v01d/Friend.ly"
stars = "https://img.shields.io/github/stars/und3fined-v01d/Friend.ly?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/und3fined-v01d/Friend.ly?style=plastic&labelColor=343b41"

[[projects]]
name = "Hydrabot"
url = "https://github.com/und3fined-v01d/hydrabot"
stars = "https://img.shields.io/github/stars/und3fined-v01d/hydrabot?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/und3fined-v01d/hydrabot?style=plastic&labelColor=343b41"

[[projects]]
name = "VSCode Theme Extractor"
url = "https://github.com/und3fined-v01d/vscode-theme-extractor"
stars = "https://img.shields.io/github/stars/und3fined-v01d/vscode-theme-extractor?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/und3fined-v01d/vscode-theme-extractor?style=plastic&labelColor=343b41"

[technologies]
react = "https://img.shields.io/badge/React-black?logo=react&style=plastic"
webpack = "https://img.shields.io/badge/Webpack-black?logo=webpack&style=plastic"
snowflake = "https://img.shields.io/badge/Snowflake-black?logo=snowflake&style=plastic"
docker = "https://img.shields.io/badge/Docker-black?logo=docker&style=plastic"
kubernetes = "https://img.shields.io/badge/Kubernetes-black?logo=kubernetes&style=plastic"
github-actions = "https://img.shields.io/badge/Github%20Actions-black?logo=github-actions&style=plastic"
google-cloud-platform = "https://img.shields.io/badge/GCP-black?logo=google-cloud&style=plastic"
typescript = "https://img.shields.io/badge/Typescript-black?logo=typescript&style=plastic"
apollo = "https://img.shields.io/badge/Apollo-black?logo=apollo-graphql&style=plastic"
heroku = "https://img.shields.io/badge/Heroku-black?logo=heroku&style=plastic"
redux = "https://img.shields.io/badge/Redux-black?logo=redux&style=plastic"
graphql = "https://img.shields.io/badge/GraphQL-black?logo=graphql&style=plastic"
tensorflow = "https://img.shields.io/badge/Tensorflow-black?logo=tensorflow&style=plastic"
sass = "https://img.shields.io/badge/Sass-black?logo=sass&style=plastic"
styled-components = "https://img.shields.io/badge/Styled%20components-black?logo=styled-components&style=plastic"
git = "https://img.shields.io/badge/Git-black?logo=git&style=plastic"
nestjs = "https://img.shields.io/badge/Nestjs-black?logo=nestjs&style=plastic"
npm = "https://img.shields.io/badge/npm-black?logo=npm&style=plastic"
brave = "https://img.shields.io/badge/Brave-black?logo=brave&style=plastic"
prettier = "https://img.shields.io/badge/Prettier-black?logo=prettier&style=plastic"
mongodb = "https://img.shields.io/badge/MongoDB-black?logo=mongodb&style=plastic"
nodejs = "https://img.shields.io/badge/Node.js-black?logo=node.js&style=plastic"
deno = "https://img.shields.io/badge/Deno-black?logo=deno&style=plastic"
ansible = "https://img.shields.io/badge/Ansible-black?logo=ansible&style=plastic"
vagrant = "https://img.shields.io/badge/Vagrant-black?logo=vagrant&style=plastic"
go = "https://img.shields.io/badge/Go-black?logo=go&style=plastic"
python = "https://img.shields.io/badge/Python-black?logo=python&style=plastic"
fastify = "https://img.shields.io/badge/Fastify-black?logo=fastify&style=plastic"
vscode = "https://img.shields.io/badge/VSCode-black?logo=visual-studio-code&style=plastic"
gatsby = "https://img.shields.io/badge/Gatsby-black?logo=gatsby&style=plastic"
amazon-aws = "https://img.shields.io/badge/AWS-black?logo=amazon-aws&style=plastic"
circleci = "https://img.shields.io/badge/CircleCI-black?logo=circleci&style=plastic"
codacy = "https://img.shields.io/badge/Codacy-black?logo=codacy&style=plastic"
cypress = "https://img.shields.io/badge/Cypress-black?logo=cypress&style=plastic"
duck-duck-go = "https://img.shields.io/badge/DuckDuckGo-black?logo=duckduckgo&style=plastic"
elastic-stack = "https://img.shields.io/badge/Elastic%20Stack-black?logo=elastic-stack&style=plastic"
eslint = "https://img.shields.io/badge/ESLint-black?logo=eslint&style=plastic"